/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/banana2.glb -o src/components/Banana2.jsx -r public -k 
Banana by Poly by Google [CC-BY] via Poly Pizza
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'
import PropTypes from 'prop-types';

export type DreiGLTF = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.MeshStandardMaterial>;
};
interface CustomMesh extends THREE.Mesh {
  originalPosition: THREE.Vector3
  directionVector: THREE.Vector3
  targetPosition: THREE.Vector3
}
interface BanananProps {
  scale: number;
  // other props if any
}
const Banana:React.FC<BanananProps> = (props: JSX.IntrinsicElements['group'],scale) => {
  const { nodes, materials } = useGLTF('/models/banana.glb') as DreiGLTF
  const group = useRef<Group | null>(null)
  Banana.propTypes = {
    scale: PropTypes.number.isRequired,
  };
  useEffect(() => {
    const groupWorldPosition = new THREE.Vector3()
    group.current?.getWorldPosition(groupWorldPosition)

    group.current?.children.forEach((mesh)=>{
      const customMesh = mesh as CustomMesh;

      customMesh.originalPosition = mesh.position.clone()
      const meshWorldPosition = new THREE.Vector3()
      mesh.getWorldPosition(meshWorldPosition)

      customMesh.directionVector = meshWorldPosition.clone().sub(groupWorldPosition).normalize()
      customMesh.targetPosition = customMesh.originalPosition.clone().add(customMesh.directionVector.clone().multiplyScalar(3))
    })
  })

  const scrollData = useScroll()
  useFrame(()=>{
    group.current?.children.forEach((mesh) => {
      if( scrollData.offset < 0.0001){
        if (mesh.name === "origin"){
          mesh.visible = true
        } else {
          mesh.visible = false
        } 
      } else {
        if (mesh.name === "origin"){
          mesh.visible = false
        } else {
          mesh.visible = true
        } 
      }

      const customMesh = mesh as CustomMesh;
      customMesh.position.x = THREE.MathUtils.lerp(
        customMesh.originalPosition.x,
        customMesh.targetPosition.x,
        scrollData.offset
      )
      customMesh.position.y = THREE.MathUtils.lerp(
        customMesh.originalPosition.y,
        customMesh.targetPosition.y,
        scrollData.offset
      )
      customMesh.position.z = THREE.MathUtils.lerp(
        customMesh.originalPosition.z,
        customMesh.targetPosition.z,
        scrollData.offset
      )
    })
  })
  return (
    <group {...props} dispose={null} ref={group}>
      <group name="origin" scale={0.042}>
        <mesh name="origin" geometry={nodes.origin.geometry} material={materials.blinn10SG} />
        <mesh name="origin_1" geometry={nodes.origin_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell" position={[0.033, 2.213, 1.346]}>
        <mesh name="pasted__pCube11_group_cell037" geometry={nodes.pasted__pCube11_group_cell037.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell037_1" geometry={nodes.pasted__pCube11_group_cell037_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell001" position={[0.023, 1.695, 0.772]}>
        <mesh name="pasted__pCube11_group_cell038" geometry={nodes.pasted__pCube11_group_cell038.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell038_1" geometry={nodes.pasted__pCube11_group_cell038_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell006" position={[-0.227, -0.778, 0.379]}>
        <mesh name="pasted__pCube11_group_cell001_1" geometry={nodes.pasted__pCube11_group_cell001_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell001_2" geometry={nodes.pasted__pCube11_group_cell001_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell009" position={[-0.248, -1.148, 0.679]}>
        <mesh name="pasted__pCube11_group_cell002" geometry={nodes.pasted__pCube11_group_cell002.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell002_1" geometry={nodes.pasted__pCube11_group_cell002_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell010" position={[0.002, 2.054, 1.171]}>
        <mesh name="pasted__pCube11_group_cell003" geometry={nodes.pasted__pCube11_group_cell003.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell003_1" geometry={nodes.pasted__pCube11_group_cell003_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell012" position={[0.108, 1.291, 0.694]}>
        <mesh name="pasted__pCube11_group_cell004" geometry={nodes.pasted__pCube11_group_cell004.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell004_1" geometry={nodes.pasted__pCube11_group_cell004_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell014" position={[-0.017, 0.097, 0.233]}>
        <mesh name="pasted__pCube11_group_cell005" geometry={nodes.pasted__pCube11_group_cell005.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell005_1" geometry={nodes.pasted__pCube11_group_cell005_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell015" position={[-0.004, 0.657, -0.074]}>
        <mesh name="pasted__pCube11_group_cell006_1" geometry={nodes.pasted__pCube11_group_cell006_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell006_2" geometry={nodes.pasted__pCube11_group_cell006_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell017" position={[0.217, -0.421, 0.294]}>
        <mesh name="pasted__pCube11_group_cell007" geometry={nodes.pasted__pCube11_group_cell007.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell007_1" geometry={nodes.pasted__pCube11_group_cell007_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell018" position={[-0.194, 0.887, 0.342]}>
        <mesh name="pasted__pCube11_group_cell008" geometry={nodes.pasted__pCube11_group_cell008.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell008_1" geometry={nodes.pasted__pCube11_group_cell008_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell020" position={[0.203, 0.717, 0.566]}>
        <mesh name="pasted__pCube11_group_cell009_1" geometry={nodes.pasted__pCube11_group_cell009_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell009_2" geometry={nodes.pasted__pCube11_group_cell009_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell021" position={[0.057, -1.654, 0.819]}>
        <mesh name="pasted__pCube11_group_cell010_1" geometry={nodes.pasted__pCube11_group_cell010_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell010_2" geometry={nodes.pasted__pCube11_group_cell010_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell023" position={[0.202, -0.817, 0.092]}>
        <mesh name="pasted__pCube11_group_cell011" geometry={nodes.pasted__pCube11_group_cell011.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell011_1" geometry={nodes.pasted__pCube11_group_cell011_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell024" position={[0.033, -1.185, 0.463]}>
        <mesh name="pasted__pCube11_group_cell012_1" geometry={nodes.pasted__pCube11_group_cell012_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell012_2" geometry={nodes.pasted__pCube11_group_cell012_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell025" position={[-0.215, -0.74, 0.036]}>
        <mesh name="pasted__pCube11_group_cell013" geometry={nodes.pasted__pCube11_group_cell013.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell013_1" geometry={nodes.pasted__pCube11_group_cell013_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell026" position={[0.098, 0.063, -0.096]}>
        <mesh name="pasted__pCube11_group_cell014_1" geometry={nodes.pasted__pCube11_group_cell014_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell014_2" geometry={nodes.pasted__pCube11_group_cell014_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell028" position={[0.121, 1.298, 0.188]}>
        <mesh name="pasted__pCube11_group_cell015_1" geometry={nodes.pasted__pCube11_group_cell015_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell015_2" geometry={nodes.pasted__pCube11_group_cell015_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell029" position={[-0.007, 1.826, 0.604]}>
        <mesh name="pasted__pCube11_group_cell016" geometry={nodes.pasted__pCube11_group_cell016.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell016_1" geometry={nodes.pasted__pCube11_group_cell016_1.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell030" position={[0.097, -1.594, 0.903]}>
        <mesh name="pasted__pCube11_group_cell017_1" geometry={nodes.pasted__pCube11_group_cell017_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell017_2" geometry={nodes.pasted__pCube11_group_cell017_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell031" position={[0.269, 0.763, 0.294]}>
        <mesh name="pasted__pCube11_group_cell018_1" geometry={nodes.pasted__pCube11_group_cell018_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell018_2" geometry={nodes.pasted__pCube11_group_cell018_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell032" position={[0.029, -1.425, 0.611]}>
        <mesh name="pasted__pCube11_group_cell019" geometry={nodes.pasted__pCube11_group_cell019.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell019_1" geometry={nodes.pasted__pCube11_group_cell019_1.geometry} material={materials.blinn2SG} />
      </group>
      <mesh name="pasted__pCube11_group_cell033" geometry={nodes.pasted__pCube11_group_cell033.geometry} material={materials.blinn10SG} position={[-0.021, 2.239, 1.414]} />
      <group name="pasted__pCube11_group_cell035" position={[-0.161, 1.317, 0.402]}>
        <mesh name="pasted__pCube11_group_cell021_1" geometry={nodes.pasted__pCube11_group_cell021_1.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell021_2" geometry={nodes.pasted__pCube11_group_cell021_2.geometry} material={materials.blinn2SG} />
      </group>
      <group name="pasted__pCube11_group_cell036" position={[-0.113, -1.472, 0.758]}>
        <mesh name="pasted__pCube11_group_cell022" geometry={nodes.pasted__pCube11_group_cell022.geometry} material={materials.blinn10SG} />
        <mesh name="pasted__pCube11_group_cell022_1" geometry={nodes.pasted__pCube11_group_cell022_1.geometry} material={materials.blinn2SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/banana.glb')

export default Banana